# -*- coding: utf-8 -*
LR_SCHEDULER = False
# START_DISP = -64
# DISP_NUM = 128
# START_DISP = -128 # for whu
# DISP_NUM = 192
START_DISP = 1
DISP_NUM = 196
MASK_OPT = False
PRE_TRAIN_OPT = False
LOAD_PRE_TRAIN_MODEL_OPT = False
